# Generated by Django 5.1.4 on 2024-12-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='co2_emitted',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
