# Generated by Django 5.1.4 on 2024-12-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0002_alter_transportation_co2_emitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='co2_saved',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='co2_emitted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
