# Generated by Django 5.1.1 on 2024-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0002_user_alter_achievement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
