# Generated by Django 5.1.4 on 2024-12-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0003_trip_co2_saved_alter_transportation_co2_emitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='co2_emitted',
        ),
    ]
