# Generated by Django 5.1.4 on 2024-12-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0004_remove_transportation_co2_emitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='travel_miles_saved',
        ),
    ]
