# Generated by Django 5.1.4 on 2024-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0005_hotel_delete_customuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='co2_saved',
            new_name='co2',
        ),
        migrations.AddField(
            model_name='trip',
            name='poeple',
            field=models.IntegerField(default=1),
        ),
    ]
