# Generated by Django 5.1.4 on 2024-12-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0006_images_rename_co2_saved_trip_co2_trip_poeple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='poeple',
            new_name='people',
        ),
    ]
