# Generated by Django 5.1.4 on 2024-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0007_uploadedplantrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedplantrip',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='uploadedplantrip',
            name='location_name',
        ),
        migrations.AddField(
            model_name='uploadedplantrip',
            name='eco_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transport_type',
            field=models.CharField(choices=[('car_petrol', 'Petrol Car'), ('car_diesel', 'Diesel Car'), ('car_electric', 'Electric Car'), ('motorbike', 'Motorbike'), ('bus_urban', 'Urban Bus'), ('bus_long_distance', 'Long-Distance Bus'), ('train_electric', 'Electric Train'), ('train_diesel', 'Diesel Train'), ('cycling_manual', 'Bicycle'), ('cycling_electric', 'Electric Bicycle'), ('walking', 'Walking'), ('airplane_short_haul', 'Short-Haul Flight'), ('airplane_long_haul', 'Long-Haul Flight'), ('ferry', 'Ferry'), ('taxi', 'Taxi'), ('ride_sharing', 'Ride Sharing'), ('truck_light', 'Light Commercial Truck'), ('truck_heavy', 'Heavy Goods Truck')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedplantrip',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uploadedplantrip',
            name='image',
            field=models.ImageField(upload_to='uploaded_images/'),
        ),
    ]
