# Generated by Django 5.1.4 on 2024-12-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0007_rename_poeple_trip_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
