# Generated by Django 5.1.1 on 2024-12-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0007_uploadedplantrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedplantrip',
            old_name='location_name',
            new_name='destination_name',
        ),
    ]
