# Generated by Django 5.1.4 on 2024-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_travel_app', '0008_remove_review_hotel_remove_trip_hotel_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Car'), ('electric_car', 'Electric Car'), ('bus', 'Bus'), ('train', 'Train'), ('cycle', 'Bicycle'), ('walk', 'Walk'), ('flight', 'Flight')], max_length=50),
        ),
    ]
